# Site settings
title: 李小怪 Blog
SEOTitle: 李小怪的博客 | lixiaoguai Blog
header-img: img/post-bg-desk.png
email: 2583250149@qq.com
description: Suffer the winter's cold wind for it bears aloft next summer's seeds.
keyword: "LZ, LZ Blog, 李哲的博客, lizhe, 李哲, HTML, CSS, Javascript, js"
url: "http://1liza.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/1liza/1liza.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "前端入门"
sidebar-avatar: /img/about-lixiaoguai.gif      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     li-zhe-25-64
github_username:    1liza
facebook_username:  
jianshu_username:   
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
#Disqus（https://disqus.com/）
#disqus_username: lixiaoguai

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 8f520fd31ebe71eda2c2                         #生成的clientID
  clientSecret: aee3609fb206b8e5812d36d4084198506965d501   #生成的clientSecret
  repo: 1liza.github.io    #仓库名称
  owner: 1liza    #github用户名
  admin: 1liza
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: 

# Google Analytics
ga_track_id: UA-167592103-1   # Format: UA-xxxxxx-xx
ga_domain: auto    # 默认的是 auto, 你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "CSDN",
        href: "https://blog.csdn.net/lixiaoguai2017"
    },{
        title: "百度前端学院",
        href: "http://ife.baidu.com/"
    }
]
